networks:
  raft-network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/24
      driver: default
services:
  node1:
    build: .
    command:
    - python
    - run_node.py
    - --node
    - 10.0.0.2
    - --cluster
    - node2,node3
    - --name
    - node1
    container_name: node1
    environment:
    - NODE=node1
    - CLUSTER=node2,node3
    networks:
      raft-network:
        ipv4_address: 10.0.0.2
    ports:
    - 3333:8080/udp
  node2:
    build: .
    command:
    - python
    - run_node.py
    - --node
    - 10.0.0.3
    - --cluster
    - node1,node3
    - --name
    - node2
    container_name: node2
    environment:
    - NODE=node2
    - CLUSTER=node1,node3
    networks:
      raft-network:
        ipv4_address: 10.0.0.3
    ports:
    - 3334:8080/udp
  node3:
    build: .
    command:
    - python
    - run_node.py
    - --node
    - 10.0.0.4
    - --cluster
    - node1,node2
    - --name
    - node3
    container_name: node3
    environment:
    - NODE=node3
    - CLUSTER=node1,node2
    networks:
      raft-network:
        ipv4_address: 10.0.0.4
    ports:
    - 3335:8080/udp
version: '3.8'
