networks:
  raft-network:
    driver: bridge
services:
  node1:
    build: .
    command:
    - python
    - run_node.py
    - --node
    - 0.0.0.0
    - --cluster
    - node2,node3,node4,node5
    container_name: node1
    environment:
    - NODE=node1
    - CLUSTER=node2,node3,node4,node5
    networks:
    - raft-network
    ports:
    - 8081:8080
  node2:
    build: .
    command:
    - python
    - run_node.py
    - --node
    - 0.0.0.0
    - --cluster
    - node1,node3,node4,node5
    container_name: node2
    environment:
    - NODE=node2
    - CLUSTER=node1,node3,node4,node5
    networks:
    - raft-network
    ports:
    - 8082:8080
  node3:
    build: .
    command:
    - python
    - run_node.py
    - --node
    - 0.0.0.0
    - --cluster
    - node1,node2,node4,node5
    container_name: node3
    environment:
    - NODE=node3
    - CLUSTER=node1,node2,node4,node5
    networks:
    - raft-network
    ports:
    - 8083:8080
  node4:
    build: .
    command:
    - python
    - run_node.py
    - --node
    - 0.0.0.0
    - --cluster
    - node1,node2,node3,node5
    container_name: node4
    environment:
    - NODE=node4
    - CLUSTER=node1,node2,node3,node5
    networks:
    - raft-network
    ports:
    - 8084:8080
  node5:
    build: .
    command:
    - python
    - run_node.py
    - --node
    - 0.0.0.0
    - --cluster
    - node1,node2,node3,node4
    container_name: node5
    environment:
    - NODE=node5
    - CLUSTER=node1,node2,node3,node4
    networks:
    - raft-network
    ports:
    - 8085:8080
version: '3.8'
